### ISSUE TITLE
Two doubts about the border-core representation idea

### ISSUE THREAD

**Issue by ClimberXIE** [MIC-DKFZ/ParticleSeg3D#3]
Hi~
Firstly thanks for your excellent work and your sharing !
I have read the the paper but still have two doubts that I want to confirm:

1. The scheme as a whole is equivalent to having nnUnet learn a two-class partition of an edge-core representation, right? And the key idea is to encorage the model to learn the internal relationship between the edge and the core area (for example, the edge always surrounds around the core area) to separate two touching particles?

2. In the border-core2instance.py file, I see :
component_seg = cc3d.connected_components(border_core_array > 0)
That is to say, for the segmented results, we use connected component analysis to find each instance. It seems we don't use the edge prediction here, for both the edge region and the core region are greater than 0 at the border_core_array, right ? So what is the difference between this and using nnUnet for semantic segmentation for 1 class directly（not use border-core）, and then searching for connected domains?

I am not sure if I have misunderstood. Looking forward to your reply.

**Comment by Karol-G** [comment]
Hey @ClimberXIE,

Thank you for your interest in our work!
Regarding your questions:

1. Yes, in order to create an instance segmentation that also works in case of touching particles we use the border core representation. The cores itself ideally never touch and thus can be used to define particles as instances. The core can then simply be dilated ("grown") into the border region to get the full segmentation for each particle.

2. In line 32 you pointed out, we are not doing yet the conversion from border-core to instances. The actual conversion happens in the method `border_core_component2instance_dilation` which is called in line 50 and 65. During development we noticed that some images we are working with are too memory intensive during the conversion. Thus, we decided to do the conversion on patches instead to avoid this issue. However, if we would just create the patches based on a grid we would probably split some instances across patches, which would lead to duplicate instances after the conversion. To avoid that we choose the patches such that they always include one entire connected component (this might be an individual particle or multiple touching ones). The line you pointed out is used to find those connected components.

I hope I was able to clarify any uncertainties. Feel free to ask any further questions!

Best regards,
Karol

**Comment by ClimberXIE** [comment]
> Hey @ClimberXIE,
> 
> Thank you for your interest in our work! Regarding your questions:
> 
> 1. Yes, in order to create an instance segmentation that also works in case of touching particles we use the border core representation. The cores itself ideally never touch and thus can be used to define particles as instances. The core can then simply be dilated ("grown") into the border region to get the full segmentation for each particle.
> 2. In line 32 you pointed out, we are not doing yet the conversion from border-core to instances. The actual conversion happens in the method `border_core_component2instance_dilation` which is called in line 50 and 65. During development we noticed that some images we are working with are too memory intensive during the conversion. Thus, we decided to do the conversion on patches instead to avoid this issue. However, if we would just create the patches based on a grid we would probably split some instances across patches, which would lead to duplicate instances after the conversion. To avoid that we choose the patches such that they always include one entire connected component (this might be an individual particle or multiple touching ones). The line you pointed out is used to find those connected components.
> 
> I hope I was able to clarify any uncertainties. Feel free to ask any further questions!
> 
> Best regards, Karol

Thanks for your prompt reply, I understand now !
Best wishes !
